### ISSUE TITLE
코드 리뷰

### ISSUE THREAD

**Issue by seungha-kim** [chiabi/react-rgb-challenge#1]
잘 하셨습니다 치혜님! context를 써서 코드 분할을 해주신 부분이 특히 좋았습니다.

제가 이 게임을 구현한다면, GameContext라는 하나의 컴포넌트에서 모든 상태를 관리하는 방식으로 구현할 것 같습니다. 제가 생각하기에는 컬러코드, 스테이지, 점수 등의 많은 것들이 결합되어 있을 수밖에 없다고 느껴져서요! 현재 컨텍스트 세 개로 나뉘어진 상태를 하나로 합쳐보는 연습을 해보시면 좋을 것 같습니다.

고생하셨습니다!

**Comment by chiabi** [comment]
넵 감사합니다ㅎㅎ
게임 규모에 비해 context나 컴포넌트가 너무 많이 나눠져서 고민이 많았는데 조언해주신대로 하나의 context로 고쳐보겠습니다👍
